[package]
name = "rymessage"
version = "0.2.0"
description = "RyMessage desktop client"
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "rymessage_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "~2.6.3", features = [] }

[dependencies]
tauri = { version = "~2.11.6", features = ["tray-icon"] }
tauri-plugin-autostart = "~2.5.1"
tauri-plugin-clipboard-manager = "~2.3.3"
